services:
    hacfi_request_dumper.controller.dump:
        class: "hacfi\RequestDumperBundle\Controller\RequestDumperController"
        arguments:
            - ~
            - ~
            - ~
            - ~
